name: human
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.9
    - flask
    - flask-login
    - flask-cors
    - gunicorn
    - pandas
    - pip
    - pillow
    - pytables
    - requests-toolbelt
    - tqdm
    - transitions
    - ruamel.yaml=0.17.17
    - bcrypt
